### ISSUE TITLE
Fail to view Work Item when updated in database

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#12]
TF26071: This work item has been updated in the work item database.
Open the latest revision.
 
Microsoft.TeamFoundation.WorkItemTracking.Client.ItemAlreadyUpdatedOnServerException: TF26071: This work item has been updated in the work item database. Open the latest revision.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Open()
   at Microsoft.TeamFoundation.WorkItemTracking.Controls.WorkItemFormControl.set_Item(WorkItem value)
   at Rowan.TfsWorkingOn.WinForm.FormWorkItem..ctor(WorkItem workItem) in C:\Users\mrowan\Desktop\TfsWitWorkingOn\WinForm\FormWorkItem.cs:line 26
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.viewToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\mrowan\Desktop\TfsWitWorkingOn\WinForm\FormSetConnection.cs:line 198
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

#### This work item was migrated from CodePlex
CodePlex work item ID: '6540'
Assigned to: 'mgrowan'
Vote count: '1'

**Comment by mgrowan** [comment]
[UnknownUser@26/11/2008]
Resolved with changeset 26437.

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
