### ISSUE TITLE
Cannot update work item if updated by someone else

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#13]
When checking in, service user updates the work item and ItemAlreadyUpdatedOnServer exception is thrown.
 
Microsoft.TeamFoundation.WorkItemTracking.Client.ItemAlreadyUpdatedOnServerException: Team Foundation could not update the work item because it was already updated by another user, it does not exist, or you do not have permission to update it. ---> System.Web.Services.Protocols.SoapException: WorkItemUpdate: The Work Item is either missing or has already been updated ---> WorkItemUpdate: The Work Item is either missing or has already been updated ---> WorkItemUpdate: The Work Item is either missing or has already been updated
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.RetryHandler.HandleSoapException(SoapException se)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.ClientService.Update(String requestId, XmlElement package, XmlElement& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at CProdStudioBackendChannel.Update(CProdStudioBackendChannel* , Boolean fBatchedSave, UInt16* bstrXMLUpdateData, UInt16** pbstrXMLUpdateData)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.HandleComException(Int32 hr)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DatastoreItemClass.Save(Boolean closeForEdit)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save()
   at Rowan.TfsWorkingOn.WinForm.FormWorkItem.Save() in C:\Users\mrowan\Desktop\TfsWitWorkingOn\WinForm\FormWorkItem.cs:line 50
   at Rowan.TfsWorkingOn.WinForm.FormWorkItem.btnSave_Click(Object sender, EventArgs e) in C:\Users\mrowan\Desktop\TfsWitWorkingOn\WinForm\FormWorkItem.cs:line 56
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

#### This work item was migrated from CodePlex
CodePlex work item ID: '6541'
Assigned to: 'mgrowan'
Vote count: '1'

**Comment by mgrowan** [comment]
[UnknownUser@26/11/2008]
Resolved with changeset 26437.

**Comment by mgrowan** [comment]
[dynamic_236@13/12/2009]
I am getting the same 

I am getting an exception while workItem.Save() , the following is the exception message 


 --> [Microsoft.TeamFoundation.WorkItemTracking.Client.ItemAlreadyUpdatedOnServerException] = {"Team Foundation could not update the work item because it was already updated by another user, it does not exist, or you do not have permission to update it."}
 
and the inner exception is:


 -->    [System.Web.Services.Protocols.SoapException] {"WorkItemUpdate: The Work Item is either missing or has already been updated ---> WorkItemUpdate: The Work Item is either missing or has already been updated ---> WorkItemUpdate: The Work Item is either missing or has already been updated"} System.Web.Services.Protocols.SoapException



the stack trace is as follows:



   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.ClientServiceProxy.Update(XmlElement package, MetadataTableHaveEntry[] metadataHave, String& dbStamp, RowSetCollection& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.ClientService.Update(String requestId, XmlElement package, XmlElement& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at CProdStudioBackendChannel.Update(CProdStudioBackendChannel* , Boolean fBatchedSave, Char* bstrXMLUpdateData, Char** pbstrXMLUpdateData)

did not find the solution

**Comment by mgrowan** [comment]
[mgrowan@15/12/2009]
Are you using the latest release version 1.1?

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
