### ISSUE TITLE
NullReferenceException when clicking Selected | Estimates

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#32]
Not sure what's causing this, but at a guess it would be when a work item that does not have an estimate is selected.
 
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Rowan.TfsWorkingOn.WorkingItem.UpdateWorkingOnEstimates()
   at Rowan.TfsWorkingOn.WinForm.FormEstimates..ctor(WorkingItem workingItem)
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.modifyEstimatesToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 
 
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
TfsWorkingOn
    Assembly Version: 1.1.3257.16505
    Win32 Version: 1.1.3257.16505
    CodeBase: file:///C:/Program%20Files%20(x86)/TFS%20Working%20On/TfsWorkingOn.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Rowan.TfsWorkingOn
    Assembly Version: 1.1.3257.16071
    Win32 Version: 1.1.3257.16071
    CodeBase: file:///C:/Program%20Files%20(x86)/TFS%20Working%20On/Rowan.TfsWorkingOn.DLL
----------------------------------------
Microsoft.TeamFoundation.Client
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.Client/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Client.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.dll
----------------------------------------
Microsoft.TeamFoundation.Common
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.Common/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Common.dll
----------------------------------------
System.Web.Services
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Services/2.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Microsoft.TeamFoundation
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
gmmtkye7
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.TeamFoundation.Common.Library
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.Common.Library/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Common.Library.dll
----------------------------------------
f1k-vdxv
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
qgcekjzr
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
fl4uqu7a
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1 built by: SP
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.dll
----------------------------------------
msvcm90
    Assembly Version: 9.0.30729.1
    Win32 Version: 9.00.30729.1
    CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_e163563597edeada/msvcm90.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.8 built by: RTM
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Proxy/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.Cache
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.8 built by: RTM
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.Cache/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.Cache.dll
----------------------------------------
sj9vtyaf
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.RuleEngine
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.8 built by: RTM
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.RuleEngine/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.RuleEngine.dll
----------------------------------------
8yt0uzk_
    Assembly Version: 1.1.3257.16071
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.QueryLanguage
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.8 built by: RTM
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.QueryLanguage/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.QueryLanguage.dll
----------------------------------------
bezspa1z
    Assembly Version: 1.1.3257.16071
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Controls
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1 built by: SP
    CodeBase: file:///C:/Program%20Files%20(x86)/TFS%20Working%20On/Microsoft.TeamFoundation.WorkItemTracking.Controls.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
_cj-ymlt
    Assembly Version: 1.1.3257.16071
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.VersionControl.Controls
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1 built by: SP
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio%209.0/Common7/IDE/PrivateAssemblies/Microsoft.TeamFoundation.VersionControl.Controls.dll
----------------------------------------
Microsoft.TeamFoundation.VersionControl.Common
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1 built by: SP
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.VersionControl.Common/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.VersionControl.Common.dll
----------------------------------------
vzofpxja
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
 
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
 
For example:
 

    

 
When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

#### This work item was migrated from CodePlex
CodePlex work item ID: '6763'
Vote count: '1'

**Comment by mgrowan** [comment]
**Issue closed by _mgrowan_ with comment**
Found that soon after that beta release :P
Has been fixed changeset 26528
