### ISSUE TITLE
Unhandled exception viewing current working on work item when connection to server is lost

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#38]
1) Start working on. 
2) Disconnect from the server
3) Select View on the selected work item.
 
Server operation timed out or server not responding. Try again.
 
Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: Server operation timed out or server not responding.  Try again. ---> System.Web.Services.Protocols.SoapException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified) ---> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.RetryHandler.HandleSoapException(SoapException se)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.ClientService.GetWorkItem(String requestId, Int32 workItemId, Int32 revisionId, Int32 minimumRevisionId, Nullable`1 asOfDate, Boolean useMaster, IWorkItemRowSets& workItem, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at CProdStudioBackendChannel.HrGetMultipleIssuesAsOf(CProdStudioBackendChannel* , Boolean fUseMasterOnly, tagVARIANT varsalObjectTypes, tagVARIANT varsalIDs, tagVARIANT varsavarAsOfs, tagVARIANT varsalRevisions, Int32* phrsWorkItem)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.HandleComException(Int32 hr)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DatastoreItemClass.Refresh()
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.SyncToLatest()
   at Rowan.TfsWorkingOn.WinForm.FormWorkItem..ctor(WorkItem workItem)
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.viewToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

#### This work item was migrated from CodePlex
CodePlex work item ID: '7029'
Assigned to: 'sca_tone'
Vote count: '0'

**Comment by mgrowan** [comment]
[UnknownUser@20/11/2010]
Associated with changeset 69660.

**Comment by mgrowan** [comment]
[UnknownUser@24/11/2010]

**Comment by mgrowan** [comment]
[UnknownUser@1/04/2011]

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
