### ISSUE TITLE
TFS 2010 hierarchical query in context menu exception

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#55]
Expecting comparison operator. The error is caused by «[System.TeamProject]».
 
Microsoft.TeamFoundation.WorkItemTracking.Client.ValidationException:  Expecting comparison operator. The error is caused by «[System.TeamProject]».
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Query.Initialize(WorkItemStore store, String wiql, IDictionary context, BatchReadParameterCollection batchReadParams, Boolean dayPrecision)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Query..ctor(WorkItemStore store, String wiql, IDictionary context, Boolean dayPrecision)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.Query(String wiql, IDictionary context)
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.queryListToolStripMenuItem_DropDownOpening(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripMenuItem.OnMouseButtonStateChange(MouseEventArgs e, Boolean isMouseDown)
   at System.Windows.Forms.ToolStripMenuItem.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

#### This work item was migrated from CodePlex
CodePlex work item ID: '11630'
Assigned to: 'mgrowan'
Vote count: '3'

**Comment by mgrowan** [comment]
[UnknownUser@17/03/2011]
Associated with changeset 74795.

**Comment by mgrowan** [comment]
[UnknownUser@17/03/2011]

**Comment by mgrowan** [comment]
[UnknownUser@17/03/2011]
Fixed an exception, but I don't think this is the same on that is occuring here.

**Comment by mgrowan** [comment]
[UnknownUser@26/04/2011]

**Comment by mgrowan** [comment]
[UnknownUser@28/04/2011]
Resolved with changeset 76982.

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
