### ISSUE TITLE
Menu Query exception when Query no longer exists

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#56]
When the menu query is set for one TFS Server and the server connection is change, or the menu query is deleted or permission removed the context menu throws an exception.
 
************** Exception Text **************
System.UnauthorizedAccessException: TF26208: The item does not exist, or you do not have permission to it. ---> System.Web.Services.Protocols.SoapException: Does not exist or access is denied. ---> Does not exist or access is denied. ---> Does not exist or access is denied.
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.ClientServiceProxy.GetStoredQuery(Guid queryId, Boolean useMaster)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.ClientService.GetStoredQuery(String requestId, Boolean useMaster, Guid queryId, RowSetCollection& queryDataSet)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Server.GetQuery(Guid guid)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Server.GetQuery(Guid guid)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.StoredQueryProvider.GetQuery(Guid guid)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.GetStoredQuery(Guid guid)
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.queryListToolStripMenuItem_DropDownOpening(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripMenuItem.OnMouseButtonStateChange(MouseEventArgs e, Boolean isMouseDown)
   at System.Windows.Forms.ToolStripMenuItem.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

#### This work item was migrated from CodePlex
CodePlex work item ID: '11671'
Assigned to: 'sca_tone'
Vote count: '1'

**Comment by mgrowan** [comment]
[UnknownUser@20/11/2010]
Associated with changeset 69661.

**Comment by mgrowan** [comment]
[UnknownUser@24/11/2010]

**Comment by mgrowan** [comment]
[UnknownUser@1/04/2011]

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
