### ISSUE TITLE
Unable to map version 1.2 to tfs 2010

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#61]
System Information:
Windows 7
Visual Studio 2010
Visual Studio 2008 SP1
Visual Studio 2008 Team explorer with forward compatibility
 
When trying to map this fields:
 
Mapping Path: http://sever:port/tfs/collection
Project = Project 
Work Item Type = Task
Duration = Microsoft.VSTS.Scheduling.OriginalEstimate
Remaning = Microsoft.VSTS.Scheduling.RemainingWork
Elapsed = Microsoft.VSTS.Scheduling.CompletedWork
 
Error:
 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
 
************** Exception Text **************
System.ArgumentException: URI formats are not supported.
   at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Rowan.TfsWorkingOn.WorkingItemConfiguration.Save()
   at Rowan.TfsWorkingOn.WinForm.FormWorkItemConfiguration.buttonSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 
 
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4952 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
TfsWorkingOn
    Assembly Version: 1.2.3896.13652
    Win32 Version: 1.2.3896.13652
    CodeBase: file:///C:/Program%20Files/TFS%20Working%20On/TfsWorkingOn.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Rowan.TfsWorkingOn
    Assembly Version: 1.2.3896.13646
    Win32 Version: 1.2.3896.13646
    CodeBase: file:///C:/Program%20Files/TFS%20Working%20On/Rowan.TfsWorkingOn.DLL
----------------------------------------
Microsoft.TeamFoundation.Client
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.4413
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.Client/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Client.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
m3zdan2c
    Assembly Version: 1.2.3896.13646
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.dll
----------------------------------------
Microsoft.TeamFoundation.Common
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.4413
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.Common/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Common.dll
----------------------------------------
Microsoft.TeamFoundation
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.4413
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.dll
----------------------------------------
System.Web.Services
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Services/2.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
tchsp74x
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4955 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.TeamFoundation.Common.Library
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.Common.Library/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Common.Library.dll
----------------------------------------
ezh3a3kc
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
7hluzjwc
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1 built by: SP
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.dll
----------------------------------------
msvcm90
    Assembly Version: 9.0.30729.4974
    Win32 Version: 9.00.30729.4974
    CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4974_none_50940634bcb759cb/msvcm90.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.8 built by: RTM
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Proxy/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.Cache
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.8 built by: RTM
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.Cache/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.Cache.dll
----------------------------------------
yujgretl
    Assembly Version: 9.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.RuleEngine
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.8 built by: RTM
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.RuleEngine/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.RuleEngine.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.4926 built by: NetFXw7
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
mxwcpog8
    Assembly Version: 1.2.3896.13646
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.TeamFoundation.WorkItemTracking.Client.QueryLanguage
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.4413 built by: QFE
    CodeBase: file:///C:/Windows/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.QueryLanguage/9.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.QueryLanguage.dll
----------------------------------------
 
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
 
For example:
 

    

 
When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

#### Attachments
[error.png](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=TFSWorkingOn&WorkItemId=12897&FileAttachmentId=3743)

#### This work item was migrated from CodePlex
CodePlex work item ID: '12897'
Vote count: '4'

**Comment by mgrowan** [comment]
[mgrowan@23/01/2011]
Mapping to a TFS Source Control path is coming. Thanks!

**Comment by mgrowan** [comment]
[UnknownUser@14/03/2011]
Duplicate #9515

**Comment by mgrowan** [comment]
[UnknownUser@20/08/2011]

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
