### ISSUE TITLE
Switching connections causes error in FormSearchWorkItems with TFS 2010 upgrade

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#62]
Open TFSWorkingOn
Switch Connection to another Team Project
Error when trying to open Search form
 
TF26193: The team project <project> does not exist. Check the team project name and try again..
 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************
Microsoft.TeamFoundation.WorkItemTracking.Client.DeniedOrNotExistException: TF26193: The team project Rowan does not exist. Check the team project name and try again. 
   at Microsoft.TeamFoundation.WorkItemTracking.Client.ProjectCollection.get_Item(String projectName)
   at Microsoft.TeamFoundation.WorkItemTracking.Controls.PickWorkItemsControl.WorkItemTypeCollection(WorkItemStore workItemStore, String portfolioDisplayName)
   at Microsoft.TeamFoundation.WorkItemTracking.Controls.PickWorkItemsControl.FillComboBoxWithTypes(ComboBox combobox, WorkItemStore workItemStore, String portfolioDisplayName)
   at Microsoft.TeamFoundation.WorkItemTracking.Controls.PickWorkItemsControl.set_PortfolioDisplayName(String value)
   at Rowan.TfsWorkingOn.WinForm.FormSearchWorkItems..ctor(WorkItemStore workItemStore, String projectName) in C:\Users\Matthew\Documents\My Projects\TfsWorkingOn\Main\TfsWorkingOn\WinForm\FormSearchWorkItems.cs:line 24
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.ShowSearchForm() in C:\Users\Matthew\Documents\My Projects\TfsWorkingOn\Main\TfsWorkingOn\WinForm\FormSetConnection.cs:line 86
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.ShowTeamProjectPicker() in C:\Users\Matthew\Documents\My Projects\TfsWorkingOn\Main\TfsWorkingOn\WinForm\FormSetConnection.cs:line 101
   at Rowan.TfsWorkingOn.WinForm.FormSetConnection.toolStripConnect_Click(Object sender, EventArgs e) in C:\Users\Matthew\Documents\My Projects\TfsWorkingOn\Main\TfsWorkingOn\WinForm\FormSetConnection.cs:line 302
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

#### This work item was migrated from CodePlex
CodePlex work item ID: '13172'
Assigned to: 'mgrowan'
Vote count: '0'

**Comment by mgrowan** [comment]
[stvnsam45@17/03/2011]
I'm having this issue as well.  Is a fix for this problem?  If I use Build 74576 I can initially set the connection, but if I change that connection I get the error that the project doesn't exist.  

Thanks you!

Steve

**Comment by mgrowan** [comment]
[mgrowan@21/03/2011]
Thanks Steve. That change set is created a fair bit of structural changes and did introduce a few bugs such as this one, which I logged. I had to get it in though, so that other developers could start working on other bits. 

If you change the connection and then restart TFS Working On, it should work on the new connection. I will certainly get this fixed as a priority.

**Comment by mgrowan** [comment]
[UnknownUser@23/03/2011]
Working On Update:Interval: 0 hours 0 minutesRemaining: 1.00 Elapsed: 0.00 Duration: 1.00

**Comment by mgrowan** [comment]
[UnknownUser@23/03/2011]

**Comment by mgrowan** [comment]
[UnknownUser@23/03/2011]
Working On Update:Interval: 0 hours 0 minutesRemaining: 0.99 Elapsed: 0.01 Duration: 1.00

**Comment by mgrowan** [comment]
[UnknownUser@23/03/2011]
Resolved with changeset 75042.

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
