### ISSUE TITLE
Icon double click on initial install

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#72]
on initial install double clicking the working on icon causes the following exception:
 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************
System.ArgumentNullException: Server must be specified before connecting.
Parameter name: Server
   at Rowan.TfsWorkingOn.Connection.Connect()
   at Rowan.TfsWorkingOn.WinForm.FormNotificationTray.ShowSearchForm()
   at Rowan.TfsWorkingOn.WinForm.FormNotificationTray.StartStop()
   at Rowan.TfsWorkingOn.WinForm.FormNotificationTray.notifyIcon_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.NotifyIcon.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.237 (RTMGDR.030319-2300)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.236 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
TfsWorkingOn
    Assembly Version: 1.3.4249.33873
    Win32 Version: 1.3.4249.33873
    CodeBase: file:///C:/Users/Tom/AppData/Local/Apps/2.0/9OQ24JNG.KZE/4L3VO66O.8DG/tfsw..tion_590a77283f6228ed_0001.0003_302560cc0578772d/TfsWorkingOn.exe
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.235 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
Rowan.TfsWorkingOn
    Assembly Version: 1.3.4249.33869
    Win32 Version: 1.3.4249.33869
    CodeBase: file:///C:/Users/Tom/AppData/Local/Apps/2.0/9OQ24JNG.KZE/4L3VO66O.8DG/tfsw..tion_590a77283f6228ed_0001.0003_302560cc0578772d/Rowan.TfsWorkingOn.DLL
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
Microsoft.TeamFoundation.Client
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.TeamFoundation.Client/10.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Client.dll
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
Microsoft.TeamFoundation.Common
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.TeamFoundation.Common/10.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Common.dll
Microsoft.TeamFoundation
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.TeamFoundation/10.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.dll
Microsoft.TeamFoundation.WorkItemTracking.Client
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.TeamFoundation.WorkItemTracking.Client/10.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.dll
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
For example:
<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

#### This work item was migrated from CodePlex
CodePlex work item ID: '14174'
Assigned to: 'cptbucky'
Vote count: '0'

**Comment by mgrowan** [comment]
[UnknownUser@9/09/2011]
Resolved with changeset 83483.

**Comment by mgrowan** [comment]
[UnknownUser@14/02/2013]

**Comment by mgrowan** [comment]
[UnknownUser@16/05/2013]
