### ISSUE TITLE
Query list is empty in configuration window

### ISSUE THREAD

**Issue by mgrowan** [mgrowan/tfs-working-on#88]
Using visual studio 2013.3 
Menu query just shown "<Select a Query>" and nothing else. When I click ellipsis button near the query dropdown, exception is shown:

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.TeamFoundation.WorkItemTracking.Controls.QueryPickerTreeControl.Initialize(Project[] projects, QueryItem selectedItem, QueryPickerType pickerType)
   at Microsoft.TeamFoundation.WorkItemTracking.Controls.QueryPickerDialog..ctor(Project[] projects, QueryItem selectedItem, QueryPickerType pickerType)
   at Microsoft.TeamFoundation.WorkItemTracking.Controls.QueryPickerControl.OnBrowse(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18449 built by: FX451RTMGDR

    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
TfsWorkingOn
Assembly Version: 1.4.5337.23038
Win32 Version: 1.4.5337.23038

    CodeBase: file:///R:/SRC/TfsWorkingOn/Main/TfsWorkingOn/WinForm/bin/Debug/TfsWorkingOn.exe
System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
System
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
Microsoft.TeamFoundation.Client
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.TeamFoundation.Client/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Client.dll
System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
Microsoft.TeamFoundation.Common
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.TeamFoundation.Common/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Common.dll
System.Configuration
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
Microsoft.VisualStudio.Services.Common
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Services.Common/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Services.Common.dll
WindowsBase
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
PresentationCore
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
Rowan.TfsWorkingOn
Assembly Version: 1.4.5337.23032
Win32 Version: 1.4.5337.23032

    CodeBase: file:///R:/SRC/TfsWorkingOn/Main/TfsWorkingOn/WinForm/bin/Debug/Rowan.TfsWorkingOn.DLL
Microsoft.GeneratedCode
Assembly Version: 1.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
Microsoft.TeamFoundation.WorkItemTracking.Client
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.TeamFoundation.WorkItemTracking.Client/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.dll
System.Runtime.Serialization
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
Microsoft.VisualStudio.Services.Client
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Services.Client/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Services.Client.dll
SMDiagnostics
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
System.Web.Services
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
System.Xml.Linq
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.17929 built by: FX45RTMREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
System.ServiceModel.Internals
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.17929 built by: FX45RTMREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
Microsoft.TeamFoundation.WorkItemTracking.Common
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.TeamFoundation.WorkItemTracking.Common/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Common.dll
Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader.dll
Microsoft.TeamFoundation.WorkItemTracking.Proxy
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.TeamFoundation.WorkItemTracking.Proxy/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll
Microsoft.TeamFoundation.WorkItemTracking.Controls
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30501.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.TeamFoundation.WorkItemTracking.Controls/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.WorkItemTracking.Controls.dll
Accessibility
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.17929 built by: FX45RTMREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
Microsoft.TeamFoundation.Controls
Assembly Version: 12.0.0.0
Win32 Version: 12.0.30723.0

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.TeamFoundation.Controls/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.TeamFoundation.Controls.dll
PresentationFramework
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.18408

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
Microsoft.TeamFoundation.WorkItemTracking.Client.Qu

#### This work item was migrated from CodePlex
CodePlex work item ID: '16947'
Vote count: '2'

**Comment by mgrowan** [comment]
[jandans1@22/09/2014]
Is there a fix for this problem? Today i stumbled upoan this problem also.... config window query list does not work any more.....

**Comment by mgrowan** [comment]
[UnknownUser@22/09/2014]
